safe:        true
port:        4000
baseurl:     /google-maps-sf-crime-vis
permalink:   pretty
#Setup
title:       SF Crime Visualization
url:         http://localhost:4000/google-maps-sf-crime-vis
future:      true

defaults: 
  - scope:
      path: ""
    values:
      layout: "SFcrime"
      type: "pages"
