safe:        true
port:        4000
baseurl:     /
permalink:   pretty
#Setup
title:       SF Crime Visualization
url:         http://localhost:4000/
future:      true

defaults: 
  - scope:
      path: ""
    values:
      layout: "SFcrime"
      type: "pages"
