safe:        true
port:        4000
host:        localhost
baseurl:     /google-maps-sf-crime-vis
permalink:   pretty
#Setup
title:       SF Crime Visualization
url:         http://localhost:4000/google-maps-sf-crime-vis
future:      true

defaults: 
  - scope:
      path: ""
    values:
      layout: "SFcrime"
      type: "pages"

exclude: ['source','node_modules','gulp','package.json','gulpfile.js','.babelrc','Gemfile','Gemfile.lock']
